apiVersion: v1
kind: Pod
metadata:
  name: counter-even
spec:
  containers:
  - name: count-even
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date)"; i=$((i+2)); sleep 1; done']