apiVersion: v1
kind: Pod
metadata:
    name: fluentd-agent-pod
spec:
    containers:
    - name: fluentd-agent
      image: jwinudemy/fluentd-alpine-sysout:v1
      env:
      # this is specified to override the default specified in Dockerfile
      - name: FLUENTD_CONF
        value: my_fluentd.conf
      volumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
      # in the minikube, this is the actual location of the container logs  
      - name: minikubemount
        mountPath: /mnt/sda1/var/lib/docker/containers
        readOnly: true
      # mount this directory in the container which will contain the custom fluentd config file  
      - name: config-volume
        mountPath: /fluentd/etc
    volumes:
      - name: varlog
        hostPath:
          path: /var/log/
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers      
      - name: minikubemount
        hostPath: 
          path: /mnt/sda1/var/lib/docker/containers
      - name: config-volume
        configMap:
          name: my-fluentd-config
